const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("node:fs");
const packageVersion = JSON.parse(fs.readFileSync("package.json")).version;
const enMessages = JSON.parse(fs.readFileSync("shared/_locales/en/messages.json", "utf8"));
const LOCALES = ["en", "es", "fr", "de", "pt", "it"];
for (const browser of ["firefox", "chrome"]) test(`${browser} manifest is valid and versions match`, () => { const manifest = JSON.parse(fs.readFileSync(`${browser}/manifest.json`)); assert.equal(manifest.version, packageVersion); assert.ok(manifest.permissions.includes("tabs")); assert.ok(manifest.permissions.includes("bookmarks")); assert.ok(manifest.permissions.includes("alarms")); });
test("Firefox loads the popular-site catalog and categories before its background listener", () => { const manifest = JSON.parse(fs.readFileSync("firefox/manifest.json")); assert.deepEqual(manifest.background.scripts, ["top-sites.js", "categories.js", "background.js"]); });
test("Dave AI is the configured default without a user-editable endpoint", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /method: "ai", provider: "dave"/); assert.doesNotMatch(fs.readFileSync("shared/options/options.html", "utf8"), /Dave AI endpoint/); });
test("permission requests start before asynchronous storage reads", () => { const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); const options = fs.readFileSync("shared/options/options.js", "utf8").split("onsubmit =")[1]; assert.ok(popup.indexOf("requestAiAccess()") < popup.indexOf("await accessRequest")); assert.ok(options.indexOf("OrganizerPermissions.request(provider)") < options.indexOf("await api.storage.local.get")); });
test("data_collection is only ever requested from a real Firefox, with a fallback if a browser rejects it anyway", () => { const permissions = fs.readFileSync("shared/permissions.js", "utf8"); assert.match(permissions, /getBrowserInfo/); assert.doesNotMatch(permissions, /if \(globalThis\.browser\)/); assert.match(permissions, /catch \(error\)/); assert.match(permissions, /data_collection/i); const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); const options = fs.readFileSync("shared/options/options.js", "utf8"); assert.doesNotMatch(popup, /data_collection/); assert.doesNotMatch(options, /data_collection/); assert.match(popup, /OrganizerPermissions\.request/); assert.match(options, /OrganizerPermissions\.request/); });
test("only the active organize button receives the loading class", () => { const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); assert.match(popup, /busy && id === activeId/); assert.match(popup, /"#organize-tabs"\);/); assert.match(popup, /"#organize-bookmarks"\);/); });
test("tabs and bookmarks share one durable, resumable AI job pipeline", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /JOB_KINDS = \["bookmarks", "tabs"\]/); assert.match(source, /function applyJob\(jobs, job\)/); assert.match(source, /function resumeJobs\(\)/); assert.match(source, /applyBookmarkJob/); assert.match(source, /applyTabJob/); assert.match(source, /startLocalApplyJob/); });
test("tab fallback defaults to reordering and optionally creates category windows", () => { const source = fs.readFileSync("shared/background.js", "utf8"); const options = fs.readFileSync("shared/options/options.html", "utf8"); assert.match(source, /tabFallback: "reorder"/); assert.match(source, /job\.tabFallback === "windows"/); assert.match(source, /api\.windows, "create"/); assert.match(source, /tabReorderOrder/); assert.match(options, /id="tab-fallback"/); assert.match(options, /value="reorder"/); assert.match(options, /value="windows"/); });
test("Dave AI submits one aggregate request while direct providers remain batched", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /startDaveJob\("bookmarks", items\)/); assert.match(source, /startDaveJob\("tabs", items, meta\)/); assert.match(source, /batchedAssignments\(payload, AI_BATCH_SIZE/); });
test("aggregate Dave AI polling cancels unfinished parent requests and enforces a client-side deadline", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /DAVE_JOB_TIMEOUT_MS = 2 \* 60 \* 60 \* 1000/); assert.match(source, /organizer\/jobs\/\$\{jobId\}\/cancel/); assert.match(source, /Date\.now\(\) > new Date\(job\.createdAt\)\.getTime\(\) \+ DAVE_JOB_TIMEOUT_MS/); assert.match(source, /finally \{/); });
test("duplicate cleanup is opt-in and runs after backups", () => { const source = fs.readFileSync("shared/background.js", "utf8"); const options = fs.readFileSync("shared/options/options.html", "utf8"); assert.match(source, /closeDuplicateTabs: false/); assert.match(source, /removeDuplicateBookmarks: false/); assert.ok(source.indexOf("await saveTabs(false)") < source.indexOf("config.closeDuplicateTabs")); assert.ok(source.indexOf("await saveBookmarks()") < source.indexOf("config.removeDuplicateBookmarks")); assert.match(options, /id="close-duplicate-tabs"/); assert.match(options, /id="remove-duplicate-bookmarks"/); });
test("bookmark reorganization defaults to loose, unfiled items and puts category folders directly in their source root", () => { const source = fs.readFileSync("shared/background.js", "utf8"); const options = fs.readFileSync("shared/options/options.html", "utf8"); assert.match(source, /bookmarkScope: "loose"/); assert.match(source, /function collectLooseBookmarks/); assert.match(source, /function collectAllBookmarks/); assert.match(source, /parentId: rootId, title: row\.category/); assert.doesNotMatch(source, /organizerFolderTitle/); assert.match(options, /id="bookmark-scope"/); });
test("folder exclusion settings default off and the second option only makes sense once the first is on", () => { const source = fs.readFileSync("shared/background.js", "utf8"); const options = fs.readFileSync("shared/options/options.html", "utf8"); const optionsJs = fs.readFileSync("shared/options/options.js", "utf8"); assert.match(source, /excludeFoldersFromOrganizing: false, organizeInsideExcludedFolders: false/); assert.match(source, /excludeFolders = false, organizeInsideExcluded = false/); assert.match(options, /id="exclude-folders"/); assert.match(options, /id="organize-inside-excluded"/); assert.match(optionsJs, /function toggleFolderScope/); assert.match(optionsJs, /organizeInsideExcludedFolders = \$\("#exclude-folders"\)\.checked && \$\("#organize-inside-excluded"\)\.checked/); });
test("folders directly in a root are sent and moved as whole units, not broken apart", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /function countBookmarksIn/); assert.match(source, /function representativeUrl/); assert.match(source, /isFolder: true/); assert.match(source, /item\.isFolder/); });
test("AI job dismissal is available so finished jobs can be cleared from storage once seen", () => { const source = fs.readFileSync("shared/background.js", "utf8"); const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); assert.match(source, /async function dismissAiJob/); assert.match(source, /message\.action === "dismissAiJob"/); assert.match(popup, /message\("dismissAiJob"/); assert.match(popup, /fade-out/); });
test("AI jobs are shown most-recently-updated first", () => { const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); assert.match(popup, /sort\(\(a, b\) => new Date\(b\.updatedAt\) - new Date\(a\.updatedAt\)\)/); });
test("bookmark restore reproduces the snapshot exactly after saving a safety backup first", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.doesNotMatch(source, /restored`/); assert.match(source, /function restoreBookmarkSnapshot/); assert.match(source, /function clearBookmarkChildren/); assert.match(source, /function recreateBookmarkNodes/); assert.doesNotMatch(source, /function mergeBookmarkNodes/); const restore = source.split("async function restoreBookmarkSnapshot")[1].split("\n}")[0]; assert.ok(restore.indexOf("await saveBookmarks()") < restore.indexOf("clearBookmarkChildren")); });
test("organizing prunes folders its moves leave empty, but never a root", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /async function pruneEmptyFolders/); assert.match(source, /protectedIds\.has\(currentId\)/); assert.match(source, /job\.pruneCandidates/); });
test("generated offline catalog contains ten thousand unique domains", () => { require("../shared/top-sites.js"); assert.equal(globalThis.OrganizerTopSites.length, 10000); assert.equal(new Set(globalThis.OrganizerTopSites).size, 10000); });
test("popup translates browser restart and AI timeout errors", () => { const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); assert.match(popup, /receiving end does not exist/i); assert.match(popup, /errorBackgroundRestarted/); assert.match(enMessages.errorBackgroundRestarted.message, /background process restarted/); assert.match(enMessages.errorBackgroundRestarted.message, /saved AI job and its latest progress/); assert.match(enMessages.errorAiTimeoutFriendly.message, /taking longer than expected/); assert.match(enMessages.bgAiTimedOut.message, /AI request timed out before every processing batch finished/); });
test("build packages explicit root entries so manifest.json is at the ZIP root", () => { const build = fs.readFileSync("scripts/build.js", "utf8"); assert.match(build, /const entries = fs\.readdirSync\(target\)/); assert.doesNotMatch(build, /\["-qr", zip, "\."\]/); assert.doesNotMatch(build, /\["-a", "-cf", zip, "\."\]/); });
test("save-and-close is described as session storage and is not styled as the primary action", () => { const html = fs.readFileSync("shared/popup/popup.html", "utf8"); const css = fs.readFileSync("shared/popup/popup.css", "utf8"); assert.match(html, /id="save-close" data-i18n="saveCloseButton">Save as session & close</); assert.doesNotMatch(html, /id="save-close" class="primary"/); assert.doesNotMatch(css, /\.actions \.primary/); assert.equal(enMessages.saveCloseButton.message, "Save as session & close"); });
test("the AI organize buttons come first in the popup and display an AI marker", () => { const html = fs.readFileSync("shared/popup/popup.html", "utf8"); const actions = html.match(/<section class="actions">(.*?)<\/section>/)[1]; assert.ok(actions.indexOf('id="organize-tabs"') < actions.indexOf('id="save-close"')); assert.ok(actions.indexOf('id="organize-bookmarks"') < actions.indexOf('id="save-close"')); assert.match(html, /id="organize-tabs">🤖 <span data-i18n="organizeTabsButton">/); assert.match(html, /id="organize-bookmarks">🤖 <span data-i18n="organizeBookmarksButton">/); });
test("restoring a saved session or backup is labeled Restore, not Open", () => { const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); assert.match(popup, /t\("restoreButton"\)/); assert.equal(enMessages.restoreButton.message, "Restore"); assert.doesNotMatch(popup, /restore\.textContent = "Open"/); });
test("popup exposes persisted AI batch progress and cancellation for both tabs and bookmarks", () => { const html = fs.readFileSync("shared/popup/popup.html", "utf8"); const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); assert.match(html, /id="ai-jobs"/); assert.match(popup, /jobStateProcessing/); assert.match(enMessages.jobStateProcessing.message, /AI processing · \$1\/\$2 batches/); assert.match(popup, /message\("cancelAiJob"/); assert.match(enMessages.aiProcessingStarted.message, /You can close this popup/); assert.match(popup, /activeAiJob\(currentAiJobs\.tabs\)/); assert.match(popup, /activeAiJob\(currentAiJobs\.bookmarks\)/); });
test("the extension is localized via the WebExtension i18n API with a browser-language default and English fallback", () => {
  for (const browser of ["firefox", "chrome"]) {
    const manifest = JSON.parse(fs.readFileSync(`${browser}/manifest.json`, "utf8"));
    assert.equal(manifest.default_locale, "en");
    assert.equal(manifest.description, "__MSG_extDescription__");
  }
  assert.ok(fs.existsSync("shared/i18n.js"));
  const enKeys = Object.keys(enMessages).sort();
  for (const locale of LOCALES) {
    const messages = JSON.parse(fs.readFileSync(`shared/_locales/${locale}/messages.json`, "utf8"));
    assert.deepEqual(Object.keys(messages).sort(), enKeys, `${locale} messages.json must define exactly the same keys as en`);
    for (const key of enKeys) assert.ok(messages[key].message.length > 0, `${locale}.${key} must not be empty`);
  }
});
