const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("node:fs");
const packageVersion = JSON.parse(fs.readFileSync("package.json")).version;
for (const browser of ["firefox", "chrome"]) test(`${browser} manifest is valid and versions match`, () => { const manifest = JSON.parse(fs.readFileSync(`${browser}/manifest.json`)); assert.equal(manifest.version, packageVersion); assert.ok(manifest.permissions.includes("tabs")); assert.ok(manifest.permissions.includes("bookmarks")); });
test("Firefox loads shared categories before its background listener", () => { const manifest = JSON.parse(fs.readFileSync("firefox/manifest.json")); assert.deepEqual(manifest.background.scripts, ["categories.js", "background.js"]); });
test("Dave AI is the configured default without a user-editable endpoint", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /method: "ai", provider: "dave"/); assert.doesNotMatch(fs.readFileSync("shared/options/options.html", "utf8"), /Dave AI endpoint/); });
test("permission requests start before asynchronous storage reads", () => { const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); const options = fs.readFileSync("shared/options/options.js", "utf8").split("onsubmit =")[1]; assert.ok(popup.indexOf("requestAiAccess()") < popup.indexOf("await accessRequest")); assert.ok(options.indexOf("api.permissions.request(request)") < options.indexOf("await api.storage.local.get")); });
test("only the active organize button receives the loading class", () => { const popup = fs.readFileSync("shared/popup/popup.js", "utf8"); assert.match(popup, /busy && id === activeId/); assert.match(popup, /"#organize-tabs"\);/); assert.match(popup, /"#organize-bookmarks"\);/); });
test("tab fallback defaults to reordering and optionally creates category windows", () => { const source = fs.readFileSync("shared/background.js", "utf8"); const options = fs.readFileSync("shared/options/options.html", "utf8"); assert.match(source, /tabFallback: "reorder"/); assert.match(source, /config\.tabFallback === "windows"/); assert.match(source, /api\.windows, "create"/); assert.match(source, /sameWindowOrder/); assert.match(options, /id="tab-fallback"/); assert.match(options, /value="reorder"/); assert.match(options, /value="windows"/); });
test("Dave AI submits one aggregate request while direct providers remain batched", () => { const source = fs.readFileSync("shared/background.js", "utf8"); assert.match(source, /config\.provider === "dave"\) return daveAI\(items/); assert.match(source, /batchedAssignments\(items, AI_BATCH_SIZE/); });
